export const SIGNUP = "register";
export const SIGNIN = "signIn";
export const GETUSER = "getUser";
export const REFFWENAMES = "patientDemographicRefferNames";
export const DEMOGRAPHIC = "patientDemographic";
export const DIAGNOSIS = "patientDiagnosis";
export const DAIGNOSISMASTER = "masterData";
export const POSTALLERGIES = "patientAllergies";
export const GETALLERGIES = "patientAllergies";
export const GETALLERGIES_REACTION = "allergiesReaction";
export const GETALLERGIES_SEVERTIES = "allergiesSeverities";
export const DELETE_ALLERGIES_SEVERTIES = "patientAllergies";
export const UPDATE_ALLERGIES_SEVERTIES = "patientAllergies";

export const FAMILY_HISTORY = "patientfamilyHistory";
export const DOCUMENT = "patientDocument"; 
export const VITALS = "patientVital";
export const DEPARTMENTS = "department";
export const COURSES = "course";
export const STUDENT = "student";
export const SCHOOL = "school";
export const FORGOT_PASSWORD = "forgotPaasword";
export const CHANGE_PASSWORD = "resetpassword";
export const PATIENTALLINFORMATION ="allPatientData";
export const CHECK_EMAIL ="checkemail";
export const SOCIAL_HISTORY ="patientSocialHistory";
export const ASSESSMENTTOOL ="assessmentTool";
export const ASSESSMENTGROUP ="assessmentGroup";
export const ASSIGNMENT ="assignment";
export const MYASSIGNMENT ="myassignment";
export const MYASSIGNMENTDETAIL ="myAssignmentDetail";
export const CUSTOM_FORM = "customForm"
export const ASSESSMENTTYPE = "assessmentType"
